### ISSUE TITLE
Out of Memory issue

### ISSUE THREAD

**Issue by jinzi98** [rubenpt91/PFL-DocVQA-Competition#14]
I want to know how much GPU the baseline is running on. I keep getting out of memory during training on two Tesla V100s（32GB * 2）. Should I keep clearing gradients during training？

**Comment by rubenpt91** [comment]
Hi @jinzi98, we used two A40 (40GB * 2) and with the current implementation we didn't have memory issues. Maybe you can try to slightly reduce the batch size to fit everything.

**Comment by jinzi98** [comment]
I seem to see the problem, but I can't fix it. I switched to an eight-card server and set client_resources = {"num_gpus": 0.8}, which according to the documentation should use 0.8 Gpus per client, but I found that only the first two Gpus were still full at runtime, while the other six Gpus were idle. The two cards add up to 32 GB * 2, which results in out of memory. How do I set it up so that all eight cards work without my OOM appearing?

**Comment by Solosneros** [comment]
Hi @jinzi98,

thanks for your questions. We would need more information:

1. Could you specify which exact configuration you are running. Are we talking about the track 1 or 2?

2. I assume you are using the exact versions of the packages that we specified? Especially which ray version are you running on?

3. When exactly is it running OOM? After one round or directly at the beginning?

> I found that only the first two Gpus were still full at runtime

I am suspecting that you are running the code and sample two clients? I am assuming that each of the gpus tries to deal with one of the clients and because no more than two clients were sampled the other GPUs are idle.

I could try to replicate your issue on our system here in Helsinki, because we have access to exactly the same GPUs as you have. However, I ran the code before opening the challenge on this system and never ran into any issues. I could execute the same command as you have if you specify to me exactly what is going wrong.

One idea would be to try to pass `ray_init_args={"local_mode": True}` to `fl.simulation.start_simulation` to run everything in one ray process and see if that helps.

**Comment by jinzi98** [comment]
Thank you for replying！
1. We are talking about T1  
2. I think the problem is that my version of the package is not quite the same as what I need, and the reason is that some of the packages I can't download through various means. My python==3.10.13, ray==2.7 and I try my best to download ray==1.11 but in vain.  Maybe because of the region or other reasons, campus network is unable to download.
3. OOM does not appear at the beginning, it tends to appear in the middle of the run. I looked at communication_log, and it appeared around the 7th round, causing the program to error.

**Comment by Solosneros** [comment]
Hi @jinzi98,

then you are observing exactly what we observed as well. Ray with a different version than the one we specify produces „zombie-processes“ that don’t release the memory after finishing training a client or when evaluating. We fixed this by downgrading the ray version. Thus, getting the exact version is crucial.

 You could try to reduce the memory leakage by calling the gc and torch empty cache at the end of the training and evaluation round but I am sure that it will remain a problem.

Another option would be to try to pass the local mode option to ray through the flower simulation function as I suggested above. Then there should be no zombie processes.

Sorry about the troubles but we didn’t anticipate that participants could download packages but then not every version of the package.

**Comment by Solosneros** [comment]
> You could try to reduce the memory leakage by calling the gc and torch empty cache at the end of the training and evaluation round but I am sure that it will remain a problem.

You might actually be able to mitigate the risk of OOM to an extent that allows you to run a sufficient amount of rounds. I still believe that the local mode might be a better option.

**Comment by Solosneros** [comment]
I close this and feel free to open if needed! :)

**Comment by Solosneros** [comment]
I close this and feel free to open if needed! :)
